# Generated by Django 4.2.7 on 2023-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereading',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
